### PR TITLE
Add ulimit -n 2048 to default DM command

### PR DESCRIPTION
**Pull request by bdevcich**
This reduces mpirun initialization overhead.

Signed-off-by: Blake Devcich <blake.devcich@hpe.com>

### CODE REVIEW

**Comment by bdevcich-hpe** [comment]
@mcfadden8

**Review by roehrich-hpe — APPROVED** [review]

**Review by mcfadden8 — APPROVED** [review]
Thank you!

**Comment by mcfadden8** [comment]
@bdevcich-hpe - This also relates to https://github.com/NearNodeFlash/nnf-dm/pull/112 right?

**Comment by bdevcich-hpe** [comment]
> @bdevcich-hpe - This also relates to #112 right?

Yes, both that PR and this one should eliminate the DM overhead that we've been seeing. I think it might be safe to close Issue #88 when both of these are merged.

**Comment by mcfadden8** [comment]
I agree.  This definitely addressed the concerns raised in #88.  Something new might come up someday, but I think that should be tracked in a different issue - IMHO

**Review by ajfloeder — APPROVED** [review]

**Pull request merged**
